LITE_IMAGE_SIZE: 256
LITE_NUM_LAYERS: 12
LITE_HIDDEN_DIM: 128
LITE_MLP_DIM: 32
LITE_NUM_HEADS: 6
LITE_PATCH_SIZE: 16
LITE_NUM_PATCHES: (image_size**2)//(patch_size**2)
LITE_FLAT_PATCHES_SHAPE: (num_patches,patch_size*patch_size*num_channels)

FULL_IMAGE_SIZE: 256
FULL_NUM_LAYERS: 12
FULL_HIDDEN_DIM: 768
FULL_MLP_DIM: 3072
FULL_NUM_HEADS: 12
FULL_PATCH_SIZE: 16
FULL_NUM_PATCHES: (image_size**2)//(patch_size**2)
FULL_FLAT_PATCHES_SHAPE: (num_patches,patch_size*patch_size*num_channels)

NUM_CLASSES: 11
DROPOUT_RATE: 0.1
NUM_CHANNELS: 3
LEARNING_RATE: 0.1
BATCH_SIZE: 16
NUM_EPOCHS: 1
