artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?export=download&id=1ylLRWqxjH-bpeFFI3YAT7kC0nBL3K2gx
  local_data_file: artifacts/data_ingestion/LaPa.tar.gz
  unzip_dir: artifacts ## Since, we are using shutil, it will make automatically unzip LaPa.tar.gz in artifacts > LaPa folder

prepare_models:
  root_dir: artifacts/prepare_model
  full_model_path: artifacts/prepare_model/full_model.keras
  lite_model_path: artifacts/prepare_model/lite_model.keras


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras
  csv_log_filepath: artifacts/prepare_callbacks/csv_log/train_log.csv


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras